using RikRealization.ClassicCast.Protocol.Media;
using Xunit;

namespace RikRealization.ClassicCast.Protocol.Tests;

public class H264AnnexBStreamTests
{
    // For VCL NALs the first payload byte carries first_mb_in_slice as Exp-Golomb.
    // 0x80 is a leading 1 bit, so ue(v) = 0: this slice starts a new picture.
    private const byte FirstSliceOfPicture = 0x80;
    // 0x42 is 0b010..., so ue(v) = 1: a slice continuing the current picture.
    private const byte ContinuationSlice = 0x42;

    /// <summary>Builds an Annex-B NAL with a four-byte start code.</summary>
    private static byte[] Nal(int type, byte firstPayloadByte = FirstSliceOfPicture) =>
        new byte[] { 0x00, 0x00, 0x00, 0x01, (byte)(type & 0x1F), firstPayloadByte, 0x42, 0x42 };

    /// <summary>Three-byte start code, which x264 uses for slice NALs.</summary>
    private static byte[] ShortNal(int type, byte firstPayloadByte = FirstSliceOfPicture) =>
        new byte[] { 0x00, 0x00, 0x01, (byte)(type & 0x1F), firstPayloadByte, 0x42, 0x42 };

    private static byte[] Concat(params byte[][] parts) =>
        parts.SelectMany(p => p).ToArray();

    [Fact]
    public void Groups_parameter_sets_with_the_following_idr()
    {
        var stream = Concat(Nal(7), Nal(8), ShortNal(5));   // SPS, PPS, IDR

        var units = H264AnnexBStream.Parse(stream);

        var unit = Assert.Single(units);
        Assert.True(unit.IsKeyFrame);
        Assert.Equal(stream.Length, unit.Length);
    }

    [Fact]
    public void Splits_consecutive_slices_into_separate_frames()
    {
        var units = H264AnnexBStream.Parse(Concat(
            Nal(7), Nal(8), ShortNal(5),   // key frame
            ShortNal(1),                   // delta
            ShortNal(1)));                 // delta

        Assert.Equal(3, units.Count);
        Assert.True(units[0].IsKeyFrame);
        Assert.False(units[1].IsKeyFrame);
        Assert.False(units[2].IsKeyFrame);
    }

    [Fact]
    public void New_parameter_sets_begin_a_new_access_unit()
    {
        var units = H264AnnexBStream.Parse(Concat(
            Nal(7), Nal(8), ShortNal(5),
            ShortNal(1),
            Nal(7), Nal(8), ShortNal(5)));   // repeat-headers on the next IDR

        Assert.Equal(3, units.Count);
        Assert.True(units[0].IsKeyFrame);
        Assert.False(units[1].IsKeyFrame);
        Assert.True(units[2].IsKeyFrame);
    }

    [Fact]
    public void Access_units_partition_the_stream_without_gaps_or_overlap()
    {
        // Every byte must end up in exactly one frame, or the decoder gets a truncated
        // bitstream and shows nothing.
        var stream = Concat(Nal(7), Nal(8), ShortNal(5), ShortNal(1), ShortNal(1));

        var units = H264AnnexBStream.Parse(stream);
        var rejoined = units.SelectMany(u => u.Data.ToArray()).ToArray();

        Assert.Equal(stream, rejoined);
    }

    [Fact]
    public void Sei_before_a_slice_stays_with_that_slice()
    {
        var units = H264AnnexBStream.Parse(Concat(
            Nal(7), Nal(8), Nal(6), ShortNal(5),
            Nal(6), ShortNal(1)));

        Assert.Equal(2, units.Count);
        Assert.True(units[0].IsKeyFrame);
    }

    [Fact]
    public void Trailing_non_vcl_data_does_not_produce_an_empty_frame()
    {
        var units = H264AnnexBStream.Parse(Concat(Nal(7), Nal(8), ShortNal(5), Nal(7), Nal(8)));

        var unit = Assert.Single(units);
        Assert.True(unit.IsKeyFrame);
    }

    [Fact]
    public void Continuation_slices_stay_in_the_same_picture()
    {
        // x264 emits one slice per thread, so a single picture routinely arrives as
        // several VCL NALs. Only the one starting at macroblock zero opens a new frame.
        var units = H264AnnexBStream.Parse(Concat(
            Nal(7), Nal(8),
            ShortNal(5, FirstSliceOfPicture),
            ShortNal(5, ContinuationSlice),
            ShortNal(5, ContinuationSlice),
            ShortNal(1, FirstSliceOfPicture),
            ShortNal(1, ContinuationSlice)));

        Assert.Equal(2, units.Count);
        Assert.True(units[0].IsKeyFrame);
        Assert.False(units[1].IsKeyFrame);
    }

    [Fact]
    public void Empty_input_yields_no_frames()
    {
        Assert.Empty(H264AnnexBStream.Parse(ReadOnlyMemory<byte>.Empty));
        Assert.Empty(H264AnnexBStream.Parse(new byte[] { 0x00, 0x00 }));
    }

    [Fact]
    public void Parses_the_real_ffmpeg_test_pattern_when_it_has_been_generated()
    {
        // Generated by tools/make-test-pattern.sh, which is deliberately not committed.
        string path = Path.Combine(AppContext.BaseDirectory,
            "..", "..", "..", "..", "..", "assets", "testpattern-1280x720.h264");

        if (!File.Exists(path)) return;

        var units = H264AnnexBStream.ParseFile(path);

        Assert.NotEmpty(units);
        Assert.All(units, u => Assert.True(u.Length > 0));

        // keyint=15 over a 2-second 30fps clip: 60 frames, every 15th a key frame.
        Assert.Equal(60, units.Count);
        Assert.Equal(4, units.Count(u => u.IsKeyFrame));
        Assert.True(units[0].IsKeyFrame, "the stream must open with a key frame");
    }
}
